addpath(fileparts(pwd));
%% Setup One Window
for i = 1:200
    setup_data(...
        'average', true, ...
        'boxcar', 10, ...
        'onset', 200, ...
        'duration', 1000, ...
        'subjects', [1,2,3,5,7,8,9,10], ...
        'dataroot', 'D:\ECoG\KyotoNaming\tmp', ...
        'cvpath', '..\cv\cvpartition_10fold_wholewindow.mat' ...
    );
end

%% Setup Opening Window
for i = 1:200
    setup_data(...
        'average', true, ...
        'boxcar', 10, ...
        'onset', 0, ...
        'duration', 50 + (10 * (i-1)), ...
        'subjects', [1,2,3,5,7,8,9,10], ...
        'dataroot', 'D:\ECoG\KyotoNaming\tmp' ...
    );
end

%% Setup Opening Window (to match "whole window" analysis)
for i = 1:100
    setup_data(...
        'average', true, ...
        'boxcar', 10, ...
        'onset', 200, ...
        'duration', 50 + (10 * (i-1)), ...
        'subjects', [1,2,3,5,7,8,9,10], ...
        'cvpath', 'cvpartition_10fold_wholewindow.mat' ...
    );
end